/*
 * Hello Neighbour
 *
 * This is the API for the 'Hello Neighbour' project inspired from the COVID-19 Global Church Hack
 *
 * API version: 0.0.3
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package service

import (
	"context"
	"errors"
	"net/http"

	"github.com/jsfan/hello-neighbour-api/internal/rest"
	"github.com/jsfan/hello-neighbour-api/internal/rest/common"
	"github.com/jsfan/hello-neighbour-api/internal/rest/model"
)

// LeaderApiService is a service that implements the logic for the LeaderApiServicer
// This service should implement the business logic for every endpoint for the LeaderApi API.
// Include any external packages or services that will be required by this service.
type LeaderApiService struct {
}

// NewLeaderApiService creates a default api service
func NewLeaderApiService() rest.LeaderApiServicer {
	return &LeaderApiService{}
}

// AddQuestion - Add question
func (s *LeaderApiService) AddQuestion(ctx context.Context, churchUUID string, body model.QuestionIn) (common.ImplResponse, error) {
	// TODO - update AddQuestion with the required logic for this service method.
	// Add api_leader_service.go to the .openapi-generator-ignore to avoid overwriting this service implementation when updating open api generation.

	//TODO: Uncomment the next line to return response Response(201, Question{}) or use other options such as http.Ok ...
	//return Response(201, Question{}), nil

	//TODO: Uncomment the next line to return response Response(400, ErrorResponse{}) or use other options such as http.Ok ...
	//return Response(400, ErrorResponse{}), nil

	//TODO: Uncomment the next line to return response Response(401, ErrorResponse{}) or use other options such as http.Ok ...
	//return Response(401, ErrorResponse{}), nil

	//TODO: Uncomment the next line to return response Response(403, ErrorResponse{}) or use other options such as http.Ok ...
	//return Response(403, ErrorResponse{}), nil

	//TODO: Uncomment the next line to return response Response(404, ErrorResponse{}) or use other options such as http.Ok ...
	//return Response(404, ErrorResponse{}), nil

	return common.Response(http.StatusNotImplemented, nil), errors.New("AddQuestion method not implemented")
}

// DeleteChurch - Delete church
func (s *LeaderApiService) DeleteChurch(ctx context.Context, churchUUID string) (common.ImplResponse, error) {
	// TODO - update DeleteChurch with the required logic for this service method.
	// Add api_leader_service.go to the .openapi-generator-ignore to avoid overwriting this service implementation when updating open api generation.

	//TODO: Uncomment the next line to return response Response(204, {}) or use other options such as http.Ok ...
	//return Response(204, nil),nil

	//TODO: Uncomment the next line to return response Response(401, ErrorResponse{}) or use other options such as http.Ok ...
	//return Response(401, ErrorResponse{}), nil

	//TODO: Uncomment the next line to return response Response(403, ErrorResponse{}) or use other options such as http.Ok ...
	//return Response(403, ErrorResponse{}), nil

	//TODO: Uncomment the next line to return response Response(404, ErrorResponse{}) or use other options such as http.Ok ...
	//return Response(404, ErrorResponse{}), nil

	return common.Response(http.StatusNotImplemented, nil), errors.New("DeleteChurch method not implemented")
}

// DeleteChurchMember - Remove member from church
func (s *LeaderApiService) DeleteChurchMember(ctx context.Context, churchUUID string, userUUID string) (common.ImplResponse, error) {
	// TODO - update DeleteChurchMember with the required logic for this service method.
	// Add api_leader_service.go to the .openapi-generator-ignore to avoid overwriting this service implementation when updating open api generation.

	//TODO: Uncomment the next line to return response Response(204, {}) or use other options such as http.Ok ...
	//return Response(204, nil),nil

	//TODO: Uncomment the next line to return response Response(401, ErrorResponse{}) or use other options such as http.Ok ...
	//return Response(401, ErrorResponse{}), nil

	//TODO: Uncomment the next line to return response Response(403, ErrorResponse{}) or use other options such as http.Ok ...
	//return Response(403, ErrorResponse{}), nil

	//TODO: Uncomment the next line to return response Response(404, ErrorResponse{}) or use other options such as http.Ok ...
	//return Response(404, ErrorResponse{}), nil

	return common.Response(http.StatusNotImplemented, nil), errors.New("DeleteChurchMember method not implemented")
}

// DeleteQuestion - Delete question
func (s *LeaderApiService) DeleteQuestion(ctx context.Context, questionUUID string) (common.ImplResponse, error) {
	// TODO - update DeleteQuestion with the required logic for this service method.
	// Add api_leader_service.go to the .openapi-generator-ignore to avoid overwriting this service implementation when updating open api generation.

	//TODO: Uncomment the next line to return response Response(204, {}) or use other options such as http.Ok ...
	//return Response(204, nil),nil

	//TODO: Uncomment the next line to return response Response(401, ErrorResponse{}) or use other options such as http.Ok ...
	//return Response(401, ErrorResponse{}), nil

	//TODO: Uncomment the next line to return response Response(403, ErrorResponse{}) or use other options such as http.Ok ...
	//return Response(403, ErrorResponse{}), nil

	//TODO: Uncomment the next line to return response Response(404, ErrorResponse{}) or use other options such as http.Ok ...
	//return Response(404, ErrorResponse{}), nil

	return common.Response(http.StatusNotImplemented, nil), errors.New("DeleteQuestion method not implemented")
}

// EditChurch - Update church details
func (s *LeaderApiService) EditChurch(ctx context.Context, churchUUID string, body model.ChurchIn) (common.ImplResponse, error) {
	// TODO - update EditChurch with the required logic for this service method.
	// Add api_leader_service.go to the .openapi-generator-ignore to avoid overwriting this service implementation when updating open api generation.

	//TODO: Uncomment the next line to return response Response(200, ChurchIn{}) or use other options such as http.Ok ...
	//return Response(200, ChurchIn{}), nil

	//TODO: Uncomment the next line to return response Response(400, ErrorResponse{}) or use other options such as http.Ok ...
	//return Response(400, ErrorResponse{}), nil

	//TODO: Uncomment the next line to return response Response(401, ErrorResponse{}) or use other options such as http.Ok ...
	//return Response(401, ErrorResponse{}), nil

	//TODO: Uncomment the next line to return response Response(404, ErrorResponse{}) or use other options such as http.Ok ...
	//return Response(404, ErrorResponse{}), nil

	return common.Response(http.StatusNotImplemented, nil), errors.New("EditChurch method not implemented")
}

// GetChurch - Retrieve details of a specific church
func (s *LeaderApiService) GetChurch(ctx context.Context, churchUUID string) (common.ImplResponse, error) {
	// TODO - update GetChurch with the required logic for this service method.
	// Add api_leader_service.go to the .openapi-generator-ignore to avoid overwriting this service implementation when updating open api generation.

	//TODO: Uncomment the next line to return response Response(200, Church{}) or use other options such as http.Ok ...
	//return Response(200, Church{}), nil

	//TODO: Uncomment the next line to return response Response(401, ErrorResponse{}) or use other options such as http.Ok ...
	//return Response(401, ErrorResponse{}), nil

	//TODO: Uncomment the next line to return response Response(403, ErrorResponse{}) or use other options such as http.Ok ...
	//return Response(403, ErrorResponse{}), nil

	//TODO: Uncomment the next line to return response Response(404, ErrorResponse{}) or use other options such as http.Ok ...
	//return Response(404, ErrorResponse{}), nil

	return common.Response(http.StatusNotImplemented, nil), errors.New("GetChurch method not implemented")
}

// GetChurchMembers - Retrieve church members
func (s *LeaderApiService) GetChurchMembers(ctx context.Context, churchUUID string) (common.ImplResponse, error) {
	// TODO - update GetChurchMembers with the required logic for this service method.
	// Add api_leader_service.go to the .openapi-generator-ignore to avoid overwriting this service implementation when updating open api generation.

	//TODO: Uncomment the next line to return response Response(200, []UserPublic{}) or use other options such as http.Ok ...
	//return Response(200, []UserPublic{}), nil

	//TODO: Uncomment the next line to return response Response(401, ErrorResponse{}) or use other options such as http.Ok ...
	//return Response(401, ErrorResponse{}), nil

	//TODO: Uncomment the next line to return response Response(403, ErrorResponse{}) or use other options such as http.Ok ...
	//return Response(403, ErrorResponse{}), nil

	//TODO: Uncomment the next line to return response Response(404, ErrorResponse{}) or use other options such as http.Ok ...
	//return Response(404, ErrorResponse{}), nil

	return common.Response(http.StatusNotImplemented, nil), errors.New("GetChurchMembers method not implemented")
}

// GetChurchQuestions - Retrieve list of all questions
func (s *LeaderApiService) GetChurchQuestions(ctx context.Context, churchUUID string) (common.ImplResponse, error) {
	// TODO - update GetChurchQuestions with the required logic for this service method.
	// Add api_leader_service.go to the .openapi-generator-ignore to avoid overwriting this service implementation when updating open api generation.

	//TODO: Uncomment the next line to return response Response(200, []Question{}) or use other options such as http.Ok ...
	//return Response(200, []Question{}), nil

	//TODO: Uncomment the next line to return response Response(401, ErrorResponse{}) or use other options such as http.Ok ...
	//return Response(401, ErrorResponse{}), nil

	//TODO: Uncomment the next line to return response Response(403, ErrorResponse{}) or use other options such as http.Ok ...
	//return Response(403, ErrorResponse{}), nil

	//TODO: Uncomment the next line to return response Response(404, ErrorResponse{}) or use other options such as http.Ok ...
	//return Response(404, ErrorResponse{}), nil

	return common.Response(http.StatusNotImplemented, nil), errors.New("GetChurchQuestions method not implemented")
}

// GetMatchGroups - Retrieve list of current match groups
func (s *LeaderApiService) GetMatchGroups(ctx context.Context, churchUUID string) (common.ImplResponse, error) {
	// TODO - update GetMatchGroups with the required logic for this service method.
	// Add api_leader_service.go to the .openapi-generator-ignore to avoid overwriting this service implementation when updating open api generation.

	//TODO: Uncomment the next line to return response Response(200, []Group{}) or use other options such as http.Ok ...
	//return Response(200, []Group{}), nil

	//TODO: Uncomment the next line to return response Response(400, ErrorResponse{}) or use other options such as http.Ok ...
	//return Response(400, ErrorResponse{}), nil

	//TODO: Uncomment the next line to return response Response(401, ErrorResponse{}) or use other options such as http.Ok ...
	//return Response(401, ErrorResponse{}), nil

	//TODO: Uncomment the next line to return response Response(403, ErrorResponse{}) or use other options such as http.Ok ...
	//return Response(403, ErrorResponse{}), nil

	//TODO: Uncomment the next line to return response Response(404, ErrorResponse{}) or use other options such as http.Ok ...
	//return Response(404, ErrorResponse{}), nil

	return common.Response(http.StatusNotImplemented, nil), errors.New("GetMatchGroups method not implemented")
}

// GetQuestion - Retrieve question
func (s *LeaderApiService) GetQuestion(ctx context.Context, questionUUID string) (common.ImplResponse, error) {
	// TODO - update GetQuestion with the required logic for this service method.
	// Add api_leader_service.go to the .openapi-generator-ignore to avoid overwriting this service implementation when updating open api generation.

	//TODO: Uncomment the next line to return response Response(200, Question{}) or use other options such as http.Ok ...
	//return Response(200, Question{}), nil

	//TODO: Uncomment the next line to return response Response(401, ErrorResponse{}) or use other options such as http.Ok ...
	//return Response(401, ErrorResponse{}), nil

	//TODO: Uncomment the next line to return response Response(403, ErrorResponse{}) or use other options such as http.Ok ...
	//return Response(403, ErrorResponse{}), nil

	//TODO: Uncomment the next line to return response Response(404, ErrorResponse{}) or use other options such as http.Ok ...
	//return Response(404, ErrorResponse{}), nil

	return common.Response(http.StatusNotImplemented, nil), errors.New("GetQuestion method not implemented")
}

// ModifyQuestion - Update question
func (s *LeaderApiService) ModifyQuestion(ctx context.Context, questionUUID string, body model.QuestionIn) (common.ImplResponse, error) {
	// TODO - update ModifyQuestion with the required logic for this service method.
	// Add api_leader_service.go to the .openapi-generator-ignore to avoid overwriting this service implementation when updating open api generation.

	//TODO: Uncomment the next line to return response Response(200, Question{}) or use other options such as http.Ok ...
	//return Response(200, Question{}), nil

	//TODO: Uncomment the next line to return response Response(400, ErrorResponse{}) or use other options such as http.Ok ...
	//return Response(400, ErrorResponse{}), nil

	//TODO: Uncomment the next line to return response Response(401, ErrorResponse{}) or use other options such as http.Ok ...
	//return Response(401, ErrorResponse{}), nil

	//TODO: Uncomment the next line to return response Response(403, ErrorResponse{}) or use other options such as http.Ok ...
	//return Response(403, ErrorResponse{}), nil

	//TODO: Uncomment the next line to return response Response(404, ErrorResponse{}) or use other options such as http.Ok ...
	//return Response(404, ErrorResponse{}), nil

	return common.Response(http.StatusNotImplemented, nil), errors.New("ModifyQuestion method not implemented")
}

// SendInvite - Send invite
func (s *LeaderApiService) SendInvite(ctx context.Context, churchUUID string, email []model.MemberInvite) (common.ImplResponse, error) {
	// TODO - update SendInvite with the required logic for this service method.
	// Add api_leader_service.go to the .openapi-generator-ignore to avoid overwriting this service implementation when updating open api generation.

	//TODO: Uncomment the next line to return response Response(204, {}) or use other options such as http.Ok ...
	//return Response(204, nil),nil

	//TODO: Uncomment the next line to return response Response(400, ErrorResponse{}) or use other options such as http.Ok ...
	//return Response(400, ErrorResponse{}), nil

	//TODO: Uncomment the next line to return response Response(401, ErrorResponse{}) or use other options such as http.Ok ...
	//return Response(401, ErrorResponse{}), nil

	//TODO: Uncomment the next line to return response Response(403, ErrorResponse{}) or use other options such as http.Ok ...
	//return Response(403, ErrorResponse{}), nil

	//TODO: Uncomment the next line to return response Response(404, ErrorResponse{}) or use other options such as http.Ok ...
	//return Response(404, ErrorResponse{}), nil

	return common.Response(http.StatusNotImplemented, nil), errors.New("SendInvite method not implemented")
}
