database:
  host: "localhost"
  port: 5432
  user: "develop"
  password: "develop"
  dbName: "helloneighbourdev"
JWTKeys:
  publicKey: helloneighbour-public.pem
  privateKey: helloneighbour-private.pem
