version: "3.7"
services:
  postgres:
    image: postgres:12-alpine
    volumes:
      - ./data:/var/lib/postgresql/data
    environment:
      - "POSTGRES_DATABASE=helloneighbourdev"
      - "POSTGRES_USER=develop"
      - "POSTGRES_PASSWORD=develop"
    ports:
      - "5432:5432"