/*
 * Hello Neighbour
 *
 * This is the API for the 'Hello Neighbour' project inspired from the COVID-19 Global Church Hack
 *
 * API version: 0.0.3
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package rest

import (
	"context"
	"net/http"
	"errors"
)

// MemberApiService is a service that implements the logic for the MemberApiServicer
// This service should implement the business logic for every endpoint for the MemberApi API.
// Include any external packages or services that will be required by this service.
type MemberApiService struct {
}

// NewMemberApiService creates a default api service
func NewMemberApiService() MemberApiServicer {
	return &MemberApiService{}
}

// AcceptInvite - Accept invite
func (s *MemberApiService) AcceptInvite(ctx context.Context, userUUID string, body UserIn) (ImplResponse, error) {
	// TODO - update AcceptInvite with the required logic for this service method.
	// Add api_member_service.go to the .openapi-generator-ignore to avoid overwriting this service implementation when updating open api generation.

	//TODO: Uncomment the next line to return response Response(200, User{}) or use other options such as http.Ok ...
	//return Response(200, User{}), nil

	//TODO: Uncomment the next line to return response Response(400, ErrorResponse{}) or use other options such as http.Ok ...
	//return Response(400, ErrorResponse{}), nil

	//TODO: Uncomment the next line to return response Response(404, ErrorResponse{}) or use other options such as http.Ok ...
	//return Response(404, ErrorResponse{}), nil

	return Response(http.StatusNotImplemented, nil), errors.New("AcceptInvite method not implemented")
}

// AddChurch - Request new church
func (s *MemberApiService) AddChurch(ctx context.Context, body ChurchIn) (ImplResponse, error) {
	// TODO - update AddChurch with the required logic for this service method.
	// Add api_member_service.go to the .openapi-generator-ignore to avoid overwriting this service implementation when updating open api generation.

	//TODO: Uncomment the next line to return response Response(204, {}) or use other options such as http.Ok ...
	//return Response(204, nil),nil

	//TODO: Uncomment the next line to return response Response(400, ErrorResponse{}) or use other options such as http.Ok ...
	//return Response(400, ErrorResponse{}), nil

	//TODO: Uncomment the next line to return response Response(401, ErrorResponse{}) or use other options such as http.Ok ...
	//return Response(401, ErrorResponse{}), nil

	return Response(http.StatusNotImplemented, nil), errors.New("AddChurch method not implemented")
}

// AddContactMethod - Add a contact method to a user profile
func (s *MemberApiService) AddContactMethod(ctx context.Context, userUUID string, body ContactMethodIn) (ImplResponse, error) {
	// TODO - update AddContactMethod with the required logic for this service method.
	// Add api_member_service.go to the .openapi-generator-ignore to avoid overwriting this service implementation when updating open api generation.

	//TODO: Uncomment the next line to return response Response(201, ContactMethod{}) or use other options such as http.Ok ...
	//return Response(201, ContactMethod{}), nil

	//TODO: Uncomment the next line to return response Response(400, ErrorResponse{}) or use other options such as http.Ok ...
	//return Response(400, ErrorResponse{}), nil

	//TODO: Uncomment the next line to return response Response(401, ErrorResponse{}) or use other options such as http.Ok ...
	//return Response(401, ErrorResponse{}), nil

	//TODO: Uncomment the next line to return response Response(403, ErrorResponse{}) or use other options such as http.Ok ...
	//return Response(403, ErrorResponse{}), nil

	return Response(http.StatusNotImplemented, nil), errors.New("AddContactMethod method not implemented")
}

// DeleteContactMethod - Delete a contact method from a user profile
func (s *MemberApiService) DeleteContactMethod(ctx context.Context, userUUID string, methodUUID string) (ImplResponse, error) {
	// TODO - update DeleteContactMethod with the required logic for this service method.
	// Add api_member_service.go to the .openapi-generator-ignore to avoid overwriting this service implementation when updating open api generation.

	//TODO: Uncomment the next line to return response Response(204, {}) or use other options such as http.Ok ...
	//return Response(204, nil),nil

	//TODO: Uncomment the next line to return response Response(400, ErrorResponse{}) or use other options such as http.Ok ...
	//return Response(400, ErrorResponse{}), nil

	//TODO: Uncomment the next line to return response Response(401, ErrorResponse{}) or use other options such as http.Ok ...
	//return Response(401, ErrorResponse{}), nil

	//TODO: Uncomment the next line to return response Response(403, ErrorResponse{}) or use other options such as http.Ok ...
	//return Response(403, ErrorResponse{}), nil

	//TODO: Uncomment the next line to return response Response(404, ErrorResponse{}) or use other options such as http.Ok ...
	//return Response(404, ErrorResponse{}), nil

	return Response(http.StatusNotImplemented, nil), errors.New("DeleteContactMethod method not implemented")
}

// DeleteUser - Delete user
func (s *MemberApiService) DeleteUser(ctx context.Context, userUUID string) (ImplResponse, error) {
	// TODO - update DeleteUser with the required logic for this service method.
	// Add api_member_service.go to the .openapi-generator-ignore to avoid overwriting this service implementation when updating open api generation.

	//TODO: Uncomment the next line to return response Response(204, {}) or use other options such as http.Ok ...
	//return Response(204, nil),nil

	//TODO: Uncomment the next line to return response Response(401, ErrorResponse{}) or use other options such as http.Ok ...
	//return Response(401, ErrorResponse{}), nil

	//TODO: Uncomment the next line to return response Response(403, ErrorResponse{}) or use other options such as http.Ok ...
	//return Response(403, ErrorResponse{}), nil

	//TODO: Uncomment the next line to return response Response(404, ErrorResponse{}) or use other options such as http.Ok ...
	//return Response(404, ErrorResponse{}), nil

	return Response(http.StatusNotImplemented, nil), errors.New("DeleteUser method not implemented")
}

// EditUser - Update user
func (s *MemberApiService) EditUser(ctx context.Context, userUUID string, body UserIn) (ImplResponse, error) {
	// TODO - update EditUser with the required logic for this service method.
	// Add api_member_service.go to the .openapi-generator-ignore to avoid overwriting this service implementation when updating open api generation.

	//TODO: Uncomment the next line to return response Response(200, User{}) or use other options such as http.Ok ...
	//return Response(200, User{}), nil

	//TODO: Uncomment the next line to return response Response(400, ErrorResponse{}) or use other options such as http.Ok ...
	//return Response(400, ErrorResponse{}), nil

	//TODO: Uncomment the next line to return response Response(401, ErrorResponse{}) or use other options such as http.Ok ...
	//return Response(401, ErrorResponse{}), nil

	//TODO: Uncomment the next line to return response Response(403, ErrorResponse{}) or use other options such as http.Ok ...
	//return Response(403, ErrorResponse{}), nil

	//TODO: Uncomment the next line to return response Response(404, ErrorResponse{}) or use other options such as http.Ok ...
	//return Response(404, ErrorResponse{}), nil

	return Response(http.StatusNotImplemented, nil), errors.New("EditUser method not implemented")
}

// GetChurches - Retrieve all signed up churches
func (s *MemberApiService) GetChurches(ctx context.Context) (ImplResponse, error) {
	// TODO - update GetChurches with the required logic for this service method.
	// Add api_member_service.go to the .openapi-generator-ignore to avoid overwriting this service implementation when updating open api generation.

	//TODO: Uncomment the next line to return response Response(200, ChurchPublic{}) or use other options such as http.Ok ...
	//return Response(200, ChurchPublic{}), nil

	//TODO: Uncomment the next line to return response Response(401, ErrorResponse{}) or use other options such as http.Ok ...
	//return Response(401, ErrorResponse{}), nil

	//TODO: Uncomment the next line to return response Response(404, ErrorResponse{}) or use other options such as http.Ok ...
	//return Response(404, ErrorResponse{}), nil

	return Response(http.StatusNotImplemented, nil), errors.New("GetChurches method not implemented")
}

// GetMatchGroup - Retrieve current match group
func (s *MemberApiService) GetMatchGroup(ctx context.Context, userUUID string) (ImplResponse, error) {
	// TODO - update GetMatchGroup with the required logic for this service method.
	// Add api_member_service.go to the .openapi-generator-ignore to avoid overwriting this service implementation when updating open api generation.

	//TODO: Uncomment the next line to return response Response(200, Group{}) or use other options such as http.Ok ...
	//return Response(200, Group{}), nil

	//TODO: Uncomment the next line to return response Response(400, ErrorResponse{}) or use other options such as http.Ok ...
	//return Response(400, ErrorResponse{}), nil

	//TODO: Uncomment the next line to return response Response(401, ErrorResponse{}) or use other options such as http.Ok ...
	//return Response(401, ErrorResponse{}), nil

	//TODO: Uncomment the next line to return response Response(403, ErrorResponse{}) or use other options such as http.Ok ...
	//return Response(403, ErrorResponse{}), nil

	//TODO: Uncomment the next line to return response Response(404, ErrorResponse{}) or use other options such as http.Ok ...
	//return Response(404, ErrorResponse{}), nil

	return Response(http.StatusNotImplemented, nil), errors.New("GetMatchGroup method not implemented")
}

// GetMessages - Retrieve all messages
func (s *MemberApiService) GetMessages(ctx context.Context, userUUID string, groupUUID string) (ImplResponse, error) {
	// TODO - update GetMessages with the required logic for this service method.
	// Add api_member_service.go to the .openapi-generator-ignore to avoid overwriting this service implementation when updating open api generation.

	//TODO: Uncomment the next line to return response Response(200, []Message{}) or use other options such as http.Ok ...
	//return Response(200, []Message{}), nil

	//TODO: Uncomment the next line to return response Response(401, ErrorResponse{}) or use other options such as http.Ok ...
	//return Response(401, ErrorResponse{}), nil

	//TODO: Uncomment the next line to return response Response(403, ErrorResponse{}) or use other options such as http.Ok ...
	//return Response(403, ErrorResponse{}), nil

	//TODO: Uncomment the next line to return response Response(404, ErrorResponse{}) or use other options such as http.Ok ...
	//return Response(404, ErrorResponse{}), nil

	return Response(http.StatusNotImplemented, nil), errors.New("GetMessages method not implemented")
}

// GetUser - Retrieve user details
func (s *MemberApiService) GetUser(ctx context.Context, userUUID string) (ImplResponse, error) {
	// TODO - update GetUser with the required logic for this service method.
	// Add api_member_service.go to the .openapi-generator-ignore to avoid overwriting this service implementation when updating open api generation.

	//TODO: Uncomment the next line to return response Response(200, User{}) or use other options such as http.Ok ...
	//return Response(200, User{}), nil

	//TODO: Uncomment the next line to return response Response(401, ErrorResponse{}) or use other options such as http.Ok ...
	//return Response(401, ErrorResponse{}), nil

	//TODO: Uncomment the next line to return response Response(403, ErrorResponse{}) or use other options such as http.Ok ...
	//return Response(403, ErrorResponse{}), nil

	//TODO: Uncomment the next line to return response Response(404, ErrorResponse{}) or use other options such as http.Ok ...
	//return Response(404, ErrorResponse{}), nil

	return Response(http.StatusNotImplemented, nil), errors.New("GetUser method not implemented")
}

// LoginUser - Login user
func (s *MemberApiService) LoginUser(ctx context.Context) (ImplResponse, error) {
	// TODO - update LoginUser with the required logic for this service method.
	// Add api_member_service.go to the .openapi-generator-ignore to avoid overwriting this service implementation when updating open api generation.

	//TODO: Uncomment the next line to return response Response(200, Jwt{}) or use other options such as http.Ok ...
	//return Response(200, Jwt{}), nil

	//TODO: Uncomment the next line to return response Response(400, ErrorResponse{}) or use other options such as http.Ok ...
	//return Response(400, ErrorResponse{}), nil

	//TODO: Uncomment the next line to return response Response(401, ErrorResponse{}) or use other options such as http.Ok ...
	//return Response(401, ErrorResponse{}), nil

	return Response(http.StatusNotImplemented, nil), errors.New("LoginUser method not implemented")
}

// SendMessage - Send message
func (s *MemberApiService) SendMessage(ctx context.Context, userUUID string, groupUUID string, body MessageIn) (ImplResponse, error) {
	// TODO - update SendMessage with the required logic for this service method.
	// Add api_member_service.go to the .openapi-generator-ignore to avoid overwriting this service implementation when updating open api generation.

	//TODO: Uncomment the next line to return response Response(201, MessageIn{}) or use other options such as http.Ok ...
	//return Response(201, MessageIn{}), nil

	//TODO: Uncomment the next line to return response Response(400, ErrorResponse{}) or use other options such as http.Ok ...
	//return Response(400, ErrorResponse{}), nil

	//TODO: Uncomment the next line to return response Response(401, ErrorResponse{}) or use other options such as http.Ok ...
	//return Response(401, ErrorResponse{}), nil

	//TODO: Uncomment the next line to return response Response(403, ErrorResponse{}) or use other options such as http.Ok ...
	//return Response(403, ErrorResponse{}), nil

	//TODO: Uncomment the next line to return response Response(404, ErrorResponse{}) or use other options such as http.Ok ...
	//return Response(404, ErrorResponse{}), nil

	return Response(http.StatusNotImplemented, nil), errors.New("SendMessage method not implemented")
}

// UpdateContactMethod - Update a contact method for a user
func (s *MemberApiService) UpdateContactMethod(ctx context.Context, userUUID string, methodUUID string, body ContactMethodIn) (ImplResponse, error) {
	// TODO - update UpdateContactMethod with the required logic for this service method.
	// Add api_member_service.go to the .openapi-generator-ignore to avoid overwriting this service implementation when updating open api generation.

	//TODO: Uncomment the next line to return response Response(200, ContactMethod{}) or use other options such as http.Ok ...
	//return Response(200, ContactMethod{}), nil

	//TODO: Uncomment the next line to return response Response(400, ErrorResponse{}) or use other options such as http.Ok ...
	//return Response(400, ErrorResponse{}), nil

	//TODO: Uncomment the next line to return response Response(401, ErrorResponse{}) or use other options such as http.Ok ...
	//return Response(401, ErrorResponse{}), nil

	//TODO: Uncomment the next line to return response Response(403, ErrorResponse{}) or use other options such as http.Ok ...
	//return Response(403, ErrorResponse{}), nil

	//TODO: Uncomment the next line to return response Response(404, ErrorResponse{}) or use other options such as http.Ok ...
	//return Response(404, ErrorResponse{}), nil

	return Response(http.StatusNotImplemented, nil), errors.New("UpdateContactMethod method not implemented")
}

// UserProfile - Logged in user&#39;s UUID and church UUID
func (s *MemberApiService) UserProfile(ctx context.Context) (ImplResponse, error) {
	// TODO - update UserProfile with the required logic for this service method.
	// Add api_member_service.go to the .openapi-generator-ignore to avoid overwriting this service implementation when updating open api generation.

	//TODO: Uncomment the next line to return response Response(200, UserProfile{}) or use other options such as http.Ok ...
	//return Response(200, UserProfile{}), nil

	//TODO: Uncomment the next line to return response Response(400, ErrorResponse{}) or use other options such as http.Ok ...
	//return Response(400, ErrorResponse{}), nil

	//TODO: Uncomment the next line to return response Response(401, ErrorResponse{}) or use other options such as http.Ok ...
	//return Response(401, ErrorResponse{}), nil

	return Response(http.StatusNotImplemented, nil), errors.New("UserProfile method not implemented")
}
