/*
 * Hello Neighbour
 *
 * This is the API for the 'Hello Neighbour' project inspired from the COVID-19 Global Church Hack
 *
 * API version: 0.0.3
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package rest

type QuestionIn struct {

	Question string `json:"question"`

	Church string `json:"church"`
}

// AssertQuestionInRequired checks if the required fields are not zero-ed
func AssertQuestionInRequired(obj QuestionIn) error {
	elements := map[string]interface{}{
		"question": obj.Question,
		"church": obj.Church,
	}
	for name, el := range elements {
		if isZero := IsZeroValue(el); isZero {
			return &RequiredError{Field: name}
		}
	}

	return nil
}

// AssertRecurseQuestionInRequired recursively checks if required fields are not zero-ed in a nested slice.
// Accepts only nested slice of QuestionIn (e.g. [][]QuestionIn), otherwise ErrTypeAssertionError is thrown.
func AssertRecurseQuestionInRequired(objSlice interface{}) error {
	return AssertRecurseInterfaceRequired(objSlice, func(obj interface{}) error {
		aQuestionIn, ok := obj.(QuestionIn)
		if !ok {
			return ErrTypeAssertionError
		}
		return AssertQuestionInRequired(aQuestionIn)
	})
}
