/*
 * COVID-19 Global Church Hack 'Hello Neighbour'
 *
 * This is the API for COVID-19 Global Church Hack 'Hello Neighbour' project
 *
 * API version: 0.0.1
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

type ErrorResponse struct {

	Code int32 `json:"code,omitempty"`

	Message string `json:"message,omitempty"`
}
