/*
 * COVID-19 Global Church Hack 'Hello Neighbour'
 *
 * This is the API for COVID-19 Global Church Hack 'Hello Neighbour' project
 *
 * API version: 0.0.1
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

import (
	"fmt"
	"net/http"
	"strings"

	"github.com/gorilla/mux"
)

type Route struct {
	Name        string
	Method      string
	Pattern     string
	HandlerFunc http.HandlerFunc
}

type Routes []Route

func NewRouter() *mux.Router {
	router := mux.NewRouter().StrictSlash(true)
	for _, route := range routes {
		var handler http.Handler
		handler = route.HandlerFunc
		handler = Logger(handler, route.Name)

		router.
			Methods(route.Method).
			Path(route.Pattern).
			Name(route.Name).
			Handler(handler)
	}

	return router
}

func Index(w http.ResponseWriter, r *http.Request) {
	fmt.Fprintf(w, "Hello World!")
}

var routes = Routes{
	Route{
		"Index",
		"GET",
		"/v0/",
		Index,
	},

	Route{
		"AddChurch",
		strings.ToUpper("Post"),
		"/v0/church",
		AddChurch,
	},

	Route{
		"AddQuestion",
		strings.ToUpper("Post"),
		"/v0/church/question",
		AddQuestion,
	},

	Route{
		"DeleteChurch",
		strings.ToUpper("Delete"),
		"/v0/church/{churchUuid}",
		DeleteChurch,
	},

	Route{
		"DeleteQuestion",
		strings.ToUpper("Delete"),
		"/v0/church/question/{questionUuid}",
		DeleteQuestion,
	},

	Route{
		"EditChurch",
		strings.ToUpper("Put"),
		"/v0/church/{churchUuid}",
		EditChurch,
	},

	Route{
		"GetChurch",
		strings.ToUpper("Get"),
		"/v0/church/{churchUuid}",
		GetChurch,
	},

	Route{
		"GetMatchGroups",
		strings.ToUpper("Get"),
		"/v0/church/matchgroups",
		GetMatchGroups,
	},

	Route{
		"GetQuestion",
		strings.ToUpper("Get"),
		"/v0/church/question/{questionUuid}",
		GetQuestion,
	},

	Route{
		"GetQuestions",
		strings.ToUpper("Get"),
		"/v0/church/question",
		GetQuestions,
	},

	Route{
		"ModifyQuestion",
		strings.ToUpper("Put"),
		"/v0/church/question/{questionUuid}",
		ModifyQuestion,
	},

	Route{
		"SendInvite",
		strings.ToUpper("Post"),
		"/v0/church/invite",
		SendInvite,
	},

	Route{
		"AddContactMethod",
		strings.ToUpper("Post"),
		"/v0/user/contactmethod",
		AddContactMethod,
	},

	Route{
		"CreateUser",
		strings.ToUpper("Post"),
		"/v0/user",
		CreateUser,
	},

	Route{
		"DeleteContactMethod",
		strings.ToUpper("Delete"),
		"/v0/user/contactmethod/{methodUuid}",
		DeleteContactMethod,
	},

	Route{
		"DeleteUser",
		strings.ToUpper("Delete"),
		"/v0/user/{userUuid}",
		DeleteUser,
	},

	Route{
		"EditUser",
		strings.ToUpper("Put"),
		"/v0/user/{userUuid}",
		EditUser,
	},

	Route{
		"GetChurchPublic",
		strings.ToUpper("Get"),
		"/v0/user/church/{churchUuid}",
		GetChurchPublic,
	},

	Route{
		"GetMatchGroup",
		strings.ToUpper("Get"),
		"/v0/user/matchgroup",
		GetMatchGroup,
	},

	Route{
		"GetMessages",
		strings.ToUpper("Get"),
		"/v0/user/bulletin",
		GetMessages,
	},

	Route{
		"GetUser",
		strings.ToUpper("Get"),
		"/v0/user/{userUuid}",
		GetUser,
	},

	Route{
		"SendMessage",
		strings.ToUpper("Post"),
		"/v0/user/bulletin",
		SendMessage,
	},

	Route{
		"UpdateContactMethod",
		strings.ToUpper("Put"),
		"/v0/user/contactmethod/{methodUuid}",
		UpdateContactMethod,
	},
}
