/*
 * COVID-19 Global Church Hack 'Hello Neighbour'
 *
 * This is the API for COVID-19 Global Church Hack 'Hello Neighbour' project
 *
 * API version: 0.0.1
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 * was /main.go
 */

package main

import (
	"log"
	"net/http"

	sw "github.com/jsfan/hello-neighbour/internal"
)

func main() {
	log.Printf("Server started")

	router := sw.NewRouter()
	router.Use(sw.AuthMiddleware)

	log.Fatal(http.ListenAndServe(":8080", router))
}
