// Code generated by OpenAPI Generator (https://openapi-generator.tech). DO NOT EDIT.
/*
 * Hello Neighbour
 *
 * This is the API for the 'Hello Neighbour' project inspired from the COVID-19 Global Church Hack
 *
 * API version: 0.0.3
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package model

import "github.com/jsfan/hello-neighbour-api/internal/rest/common"

type Message struct {
	Group string `json:"group"`

	User string `json:"user"`

	Sent string `json:"sent"`

	Message string `json:"message"`

	Uuid string `json:"uuid"`
}

// AssertMessageRequired checks if the required fields are not zero-ed
func AssertMessageRequired(obj Message) error {
	elements := map[string]interface{}{
		"group":   obj.Group,
		"user":    obj.User,
		"sent":    obj.Sent,
		"message": obj.Message,
		"uuid":    obj.Uuid,
	}
	for name, el := range elements {
		if isZero := common.IsZeroValue(el); isZero {
			return &common.RequiredError{Field: name}
		}
	}

	return nil
}

// AssertRecurseMessageRequired recursively checks if required fields are not zero-ed in a nested slice.
// Accepts only nested slice of Message (e.g. [][]Message), otherwise ErrTypeAssertionError is thrown.
func AssertRecurseMessageRequired(objSlice interface{}) error {
	return common.AssertRecurseInterfaceRequired(objSlice, func(obj interface{}) error {
		aMessage, ok := obj.(Message)
		if !ok {
			return common.ErrTypeAssertionError
		}
		return AssertMessageRequired(aMessage)
	})
}
