/*
 * COVID-19 Global Church Hack 'Hello Neighbour'
 *
 * This is the API for COVID-19 Global Church Hack 'Hello Neighbour' project
 *
 * API version: 0.0.1
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 * was: go/model_group.go
 */

package pkg

type Group struct {
	Uuid string `json:"uuid,omitempty"`

	Created string `json:"created,omitempty"`

	Users []UserPublic `json:"users,omitempty"`
}
