/*
 * COVID-19 Global Church Hack 'Hello Neighbour'
 *
 * This is the API for COVID-19 Global Church Hack 'Hello Neighbour' project
 *
 * API version: 0.0.1
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 * was: go/model_contact_method.go
 */

package pkg

type ContactMethod struct {

	Label string `json:"label,omitempty"`

	ContactDetails string `json:"contactDetails,omitempty"`

	User string `json:"user,omitempty"`

	Uuid string `json:"uuid,omitempty"`
}
