/*
 * COVID-19 Global Church Hack 'Hello Neighbour'
 *
 * This is the API for COVID-19 Global Church Hack 'Hello Neighbour' project
 *
 * API version: 0.0.1
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 * was: go/model_church.go
 */

package pkg

type Church struct {

	Name string `json:"name,omitempty"`

	Description string `json:"description,omitempty"`

	Address string `json:"address,omitempty"`

	Website string `json:"website,omitempty"`

	Email string `json:"email,omitempty"`

	Phone string `json:"phone,omitempty"`

	MainContact string `json:"main_contact,omitempty"`

	GroupSize int32 `json:"group_size,omitempty"`

	SameGender bool `json:"same_gender,omitempty"`

	MinAge int32 `json:"min_age,omitempty"`

	Uuid string `json:"uuid,omitempty"`
}
