/*
 * COVID-19 Global Church Hack 'Hello Neighbour'
 *
 * This is the API for COVID-19 Global Church Hack 'Hello Neighbour' project
 *
 * API version: 0.0.1
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 * was: go/model_message.go
 */

package pkg

type Message struct {

	Group string `json:"group,omitempty"`

	User string `json:"user,omitempty"`

	Sent string `json:"sent,omitempty"`

	Message string `json:"message,omitempty"`

	Uuid string `json:"uuid,omitempty"`
}
