on: [push, pull_request]
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: gofmt
        uses: Jerome1337/gofmt-action@v1.0.2
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: go test
