on: [push, pull_request]
jobs:
  gofmt:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: Jerome1337/gofmt-action@v1.0.2
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
        with:
          go-version: '^1.17'
      - run: |
          go generate ./...
          go test ./...
